### ISSUE TITLE
XBWrite expression not allowed #1: 'Root/Intermediate[X/Y='Passed']/Child'

### ISSUE THREAD

**Issue by SvenEwald** [SvenEwald/xmlbeam#40]
Same error as `Root/Intermediate[X/Y='Passed']` 

Relevant error message is:
...
Caused by: org.xmlbeam.util.intern.duplex.XBXPathExprNotAllowedForWriting: Not expetced here.: Node PathExpr is not supported for writing expressions in line 1 col 18 to 21
...

**Comment by SvenEwald** [comment]
The reason for this error is that path expressions (or even functions) within predicates are not supported right now. This is because I was not sure if there would be a use case for that. Technically it should be possible, but the addition of simple predicates to writing expressions was already a trade of between usefulness and effort ;-)

@zhsc If you have a real life problem that needs these kind of predicates, please let me know. Right now I have a feeling that not many people use writing expressions at all.

**Comment by zhsc** [comment]
Hi Sven, first let me say thank you for this great library it's proven very useful and flexible.

I imagine most people are using XPath for consumption of documents rather than generation, but it is very useful to be able to use the same projections for creating tests and for integrations where you have to send as well.

As far as my use case, I'm having to generate ACORD format XML which is a popular standard in the Insurance industry for exchange of data.

They commonly use a pattern like this:
```
<ClaimsParty>
    <ClaimsPartyInfo>
        <ClaimsPartyRoleCd>Something</ClaimsPartyRoleCd>
    <ClaimsPartyInfo>
    <GeneralPartyInfo>
        <NameInfo>
            <PersonName>
                <GivenName>John</GivenName>
                <Surname>Doe</Surname>
            </PersonName>
        </NameInfo>
    </GeneralPartyInfo>
</ClaimsParty>
```
So, as you can see you have to select the root element `<ClaimsParty>` using a selector with multiple path segments to get down to the `ClaimsPartyRoleCd`.  This isn't a problem for reading obviously, but does complicate writing.

I've been able to work around the issue by using the template feature and `@XBDocURL` to "seed" the basic structure of the XML.

Then for the `@XBWrite`, I've basically just added another element under the root in a different namespace (i.e. `ClaimsParty[x:RoleCode='Something']`) so the setter only selects the nodes it's generated.

It works, but is a little convoluted.  

I wanted to report it to you since it seemed like it worked in some cases so I wasn't sure if it was a bug or a known limitation.

Maybe could add a note about this limitation on the documentation page where you talk about the restrictions for writing?

Thanks!

**Comment by SvenEwald** [comment]
I decided to handle your examples as bugs and fixed them. In the next release, your unit tests will pass. I started the whole project because other DOM libraries were missing convenience and "automagic" features. So the whole point XMLBeam was from the beginning to have a "do what I mean"-library. Unexpected results should be avoided.

**Comment by zhsc** [comment]
Again thank you!  Great library, great author. :-)
